### PR TITLE
Update sentence casing for buttons

### PR DESCRIPTION
**Pull request by ncksllvn**
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18996

This PR updates the sentence casing for buttons across the website. A few are React component, and are being worked on this [vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10292), but most are here in vagov-content.

I'm not a content editor myself, so I'm not the right person to make these changes. I quickly identified instances of HTML buttons by doing a text search for `usa-button` and then checking the letter case of the text, but I don't know if I updated each correctly or I missed anything. A content editor should own this from here.

These two buttons are in Drupal content, should be updated in Drupal -

/health-care/about-va-health-benefits/dental-care/
/health-care/order-hearing-aid-batteries-prosthetic-socks/

### CODE REVIEW

**Comment by ncksllvn** [comment]
Dang it, I hit merge when I mean to just update the branch! It think this is okay, though. @bethpotts @RLHecht these sentence case updates will on [Staging](https://staging.va.gov) in 30 minutes - can you QA there and see if we need to make any adjustments? I'm sure we missed one or two but I think we got the bulk of them.

**Comment by bethpotts** [comment]
@ncksllvn Sure, we can look on staging. I was cracking up when I saw that you'd merged, Nick! But all looks good to me from scrolling through `Files changed` so I think we're good. But we'll check out staging. What about these two that didn't seem to be sentence cased when I previewed? (I'll look on staging and make sure I didn't just miss it): 
https://www.va.gov/disability/eligibility/
https://www.va.gov/disability/how-to-file-claim/

**Comment by ncksllvn** [comment]
@bethpotts I was pretty confused when it said `merged` all of a sudden lol.

Oh no! I missed those. That's in a React widget. I'll get those now and request your review.

**Comment by bethpotts** [comment]
@ncksllvn How can we identify the other react widgets?
I know there are others...

**Comment by ncksllvn** [comment]
@bethpotts One way would be if you reload the page, if there is a spinner indicator visible just before the green button renders on the screen. Is so, then it's a React/JavaScript widget of some sort.

---

Should we update the sentence casing of the navigation bar while I'm at it?

image

**Comment by ncksllvn** [comment]
Next vets-website PR, https://github.com/department-of-veterans-affairs/vets-website/pull/10306

**Comment by bethpotts** [comment]
You're a total saint, yes, could you update "Contact us" and "Sign in." That's the cherry on top of my 4 years of work on the Vets contract.

**Pull request merged**
