### PR TITLE
Renaming page URL to additional forms

### PR DESCRIPTION
**Pull request by peggygannon**
## Page to edit
/disability/how-to-file-claim/supplemental-forms

## Description of what's needed (edits/link changes/additions)
Update page name/URL from /supplemental-forms/ to /additional-forms/

### CODE REVIEW

**Comment by peggygannon** [comment]
Hi, @ncksllvn here's the PR where I updated the file URL for Supplemental forms. From: /how-to-file-claim/supplemental-forms/ TO /how-to-file-claim/additional-forms.

**Comment by ncksllvn** [comment]
Hey @peggygannon, looks like there are a bunch of links to `/disability/how-to-file-claim/supplemental-forms/` that need to be updated before we can merge this.

**Comment by peggygannon** [comment]
@ncksllvn OK, thanks. I'll update them today. sorry, this message about the broken links didn't show up for me yesterday.

**Comment by peggygannon** [comment]
@ncksllvn thanks for your help on this PR! This is ready for your review and merge when you get a chance.

**Comment by ncksllvn** [comment]
Thanks @peggygannon, will do. Coordinating with Devops now to make sure this ships at the same time as the redirect update.

**Pull request merged**
