### PR TITLE
Update banner.yml

### PR DESCRIPTION
**Pull request by Hampshire100**
Removing disaster information and updating COVID 19 information with link to vaccination page.

## Page to edit
url:

### CODE REVIEW

**Comment by ncksllvn** [comment]
Hey Josh here is a screenshot of how this looks currently

image

**Comment by Hampshire100** [comment]
HI Nick 
That looks good. Could we break VA to the last line so the link is all together?
Thank you
Josh

**Comment by ncksllvn** [comment]
Here it is w/an update title (an update I was instructed to make)

image

**Comment by ncksllvn** [comment]
@Hampshire100 I don't think I can add a link break there w/o affecting the meaning of the paragraph (how a screenreader might read it)

**Comment by ncksllvn** [comment]
On smaller screens though it collapses nicely

image

**Review by ncksllvn — APPROVED** [review]

**Pull request merged**
