### PR TITLE
content/wip/sentence casing top nav

### PR DESCRIPTION
**Pull request by bethpotts**
## Page to edit
url: all of top nav

## Origin of request (internal/stakeholder/user feedback)
Jennifer Lee

## Description of what's needed (edits/link changes/additions)
Sentence case all labels, except uppercase proper nouns

### CODE REVIEW

**Comment by bethpotts** [comment]
@ncksllvn I made the top nav changes and need Peggy to review my edits before this moves forward, but I have a question about where to make two updates:

sentence casing Qs

**Comment by bethpotts** [comment]
@peggygannon When you review this, especially watch for places where I may have lowercase a proper noun or what you think might be a proper noun. There's a gray area with those, so would love your double check on that.

**Comment by ncksllvn** [comment]
Hey @bethpotts, those have been referred to as "promos" and were requested to be editable separately from the rest of the menu. They're in the `fragments/promotions` directory. [Here's](https://github.com/department-of-veterans-affairs/vagov-content/blob/master/fragments/promotions/records.yml) the one for Records.

**Comment by ncksllvn** [comment]
@bethpotts Oof, just read your update. Dang it, that "all" is all the way in the Design System! I'll have to take that piece of it.

**Comment by peggygannon** [comment]
@ncksllvn Hi, Nick. this PR is ready for your review and then merge! Thank you!

**Pull request merged**
