### PR TITLE
Update content heading markup for proper page hierarchy

### PR DESCRIPTION
**Pull request by longmd**
## Page to edit
url: staging.va.gov/hrt/

## Origin of request (internal/stakeholder/user feedback)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38202

## Description of what's needed (edits/link changes/additions)
Content markup edits for proper a11y hierarchy

### CODE REVIEW

**Review by tmac9494 — APPROVED** [review]

**Comment by longmd** [comment]
@timwright12 , not sure if you're the one to ask about this. But do we have any idea why the continuous integration is failing and the commit cannot be built?

**Comment by timwright12** [comment]
@longmd yeah don't worry about that in this repo, Jenkins/CI doesn't block the merge so you're fine

**Comment by longmd** [comment]
> @longmd yeah don't worry about that in this repo, Jenkins/CI doesn't block the merge so you're fine

Awesome! Thanks @timwright12 . As this is my first venture into this repo, what is the staging deployment schedule for this one after PRs have been merged?

**Comment by timwright12** [comment]
@longmd this one should go out to staging the next time there's a deploy from content-build (we don't have a specific deploy for this repo since it's just added in with the metalsmith build). I don't think it will go out to prod though, because the frontmatter in the file has `vagovprod` set to `false` - otherwise it would go to prod tomorrow with content-build

**Comment by longmd** [comment]
@timwright12 , thats a great explanation. Thank you! Side note with this page: it is being used for user testing only and is not intended for PROD use, so no worries on that.

**Pull request merged**
