### PR TITLE
updating per feedback

### PR DESCRIPTION
**Pull request by DanielleSoCompany**

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @peggygannon. Could you take a look at this and let me know if you see anything incorrect or concerning w/ the updates? A couple of notes below:

- Updated subheads and button text to speak to "add a dependent" so that's clear. And then body copy speaks to the specifics of "file a claim for additional compensation...". I think this works nicely for the button too because when the user goes to eBenefits, that page is titled "Add or Remove a Dependent" so the language is consistent now.
- Also changed incidences of "applied" to "filed" re: disability compensation and made a few other minor tweaks.

**Comment by peggygannon** [comment]
@DanielleSoCompany 
I think the changes look good. However, I'm wondering if we want to tweak the intro paragraph a bit?  When I read the first sentence it makes it sound like if you want more compensation, then you should just add a dependent to your benefits. 
I'm also concerned that stakeholders might have an issue with the first sentence. Let me know your thoughts.. 

"Adding dependents to your VA disability benefits may make you eligible to receive a higher compensation payment (also called a benefit rate)."

**Comment by DanielleSoCompany** [comment]
Great point you raise, @peggygannon. I'll take a look at that paragraph again now and see if I can tweak it, and will send revised over to you for thoughts. Thanks!

**Comment by DanielleSoCompany** [comment]
Thanks, @peggygannon!

**Pull request merged**
