### PR TITLE
generate coronovirus-screener app

### PR DESCRIPTION
**Pull request by mchelen-gov**
## Page to edit
url:

### CODE REVIEW

**Comment by batemapf** [comment]
@mchelen-gov i think we can nix this one right?

**Comment by mchelen-gov** [comment]
this was generated by yeoman, wasn't certain what its purpose was? feel free to close if unnecessary

**Comment by batemapf** [comment]
i'm thinking in maybe an older version of the build process, the app landing pages were stored in here. but based on what i just added to `registry.json` over in `vets-website`, i bet this landing page is unnecessary / potentially conflicting. @ncksllvn what says you?

**Comment by ncksllvn** [comment]
I think you're right @batemapf! I think the generator just needs to be updated

**Comment by mchelen-gov** [comment]
opened issue for generator: https://github.com/department-of-veterans-affairs/generator-vets-website/issues/20

**Pull request closed without merging**
