### PR TITLE
Move non-content files from pages into assets directory

### PR DESCRIPTION
**Pull request by ncksllvn**
This pull request moves non-content files out of the pages directory and into assets. Those files were causing some issues with the link-checker running during the watch task. I suspect this is why the link-checker was disabled during watch to begin with.

Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14765

### CODE REVIEW

**Comment by jbalboni** [comment]
I wonder if any direct links to these files exist out in the wild?

**Comment by ncksllvn** [comment]
@jbalboni do you mean direct links to the download on GH?

**Comment by jbalboni** [comment]
No, I mean I wonder if other, non-vets.gov sites link to these files directly. It doesn't matter since you aren't change the urls, but could be something we have to account for later.

**Comment by ncksllvn** [comment]
Ah good point. Sounds like we may need even more redirects 😆

**Pull request merged**
