### PR TITLE
Va gov/content wip move file a claim edits to new directory

### PR DESCRIPTION
**Pull request by ncksllvn**

### CODE REVIEW

**Comment by bethpotts** [comment]
Thanks, @peggygannon ! The title just changed its name on preview... to: How to File a VA Disability Claim. So it's all good.

**Comment by ncksllvn** [comment]
I haven't look into it, but there appears to be a broken link here -

```
Error: You have 1 broken links:
       
       disability/eligibility/index.html >>> href: "/disability-benefits/apply/", text: "Learn more about how to file a claim for disability compensation"
           at maybeThrow (/tmp/vagov-apps/node_modules/metalsmith-broken-link-checker/src/handle-links.js:17:11)
           at /tmp/vagov-apps/node_modules/metalsmith-broken-link-checker/src/handle-links.js:26:7
```

**Comment by bethpotts** [comment]
@ncksllvn I fixed that broken link on the eligibility page. Can you help now with the conflicting file?

Please don't merge until @jbalboni can confirm that this PR won't overwrite the green buttons on these two pages as they currently exist (correctly) on preview--even though there's an edit within the react file:
eligiblity
how-to-file-claim

**Comment by jbalboni** [comment]
@bethpotts The changes to the eligibility page did add the duplicate button back, I went ahead and removed it here.

**Pull request merged**
