### PR TITLE
Hurricane Dorian Update

### PR DESCRIPTION
**Pull request by Hampshire100**
All
I have added the approved language for the national alert for Hurricane Dorian. I wanted to have a break between the Caribbean healthcare info and the Sunshine Healthcare info. I wasn't sure if I should use <br> tags or just hit return. Anyways I went with hitting return. If <br> is the right answer please insert a <br> between the two paragraphs. If you have any questions please call me at 603-339-2269.
Thank you in advance
Josh Tuscher

## Page to edit
url:

### CODE REVIEW

**Comment by Hampshire100** [comment]
All
This needs to be live ASAP. Senior leadership is getting impatient.

**Comment by ncksllvn** [comment]
Moving as fast as we can @Hampshire100

**Comment by Hampshire100** [comment]
Thanks Nick. Sorry to be the nudge.

**Comment by Hampshire100** [comment]
Hey team
I am being asked what the status of the promotion is. I am going to tell  them that the changes have been pushed and we are waiting for the changes to propagate the production environment. 
Is that accurate?

Thank you
Josh Tuscher

**Comment by ncksllvn** [comment]
Hey @Hampshire100, yes, that is accurate! This request became sort of tied up in our CMS work and GitHub, but this is our highest priority right now

**Comment by Hampshire100** [comment]
Hi @ncksllvn 
Thanks for the update. Ill send my update. 
Talk to you soon
Josh

**Comment by ncksllvn** [comment]
This is deploying to production right now and will be live within 10 minutes

**Comment by ncksllvn** [comment]
Banner is live!

**Comment by Hampshire100** [comment]
Thanks @ncksllvn

**Pull request merged**
