### PR TITLE
Content-wip-disability-5103-notice-update

### PR DESCRIPTION
**Pull request by peggygannon**
## Page to edit
- [ ] https://www.va.gov/disability/how-to-file-claim/evidence-needed/standard-claims/
- [ ] https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/
- [ ] https://www.va.gov/disability/how-to-file-claim/supplemental-forms/
- [ ] update left nav TO: "Additional Forms"
- [ ] update left nav under "Manage Benefits" to "Additional Forms"
 - [ ] Update header on Disability index hub
- [ ]  add PTSD form to PTSD page
- [ ]  add IU forms to Individual Unemployability page
- [ ] add A&A form to A&A page

## Origin of request (internal/stakeholder/user feedback)
SME request to make updates throughout Disability section regarding 5103 notice and updating "Supplemental Forms" page to distinguish it from Appeals.

### CODE REVIEW

**Comment by peggygannon** [comment]
@bethpotts This PR is ready for you review. I've created a redirect ticket for Devops to put in place for Supplemental Forms page to happen at the same time this PR is merged.

**Comment by bethpotts** [comment]
@ncksllvn We need your help implementing a jump link from the short url disability-evidence that'll get added to some forms. The short url will go to this va.gov page: /disability/how-to-file-claim/evidence-needed.md. Peggy added the alias redirect, and I wanted to double check that it's correct to have it as a relative link there in the front matter even though the user will click the short url on a form and be taken to the website. Not sure if that detail matters. I added the span code to the evidence-needed file where the jump link will land the user. It's <span id="evidence-show"></span>. We need your help with the redirect, getting it to go there. Thanks! And ping me to clarify any of this.

**Comment by ncksllvn** [comment]
- [ ] @amycesal to update PDF from `va.gov/benefits` to `va.gov/disability-evidence`
- [ ] If the user is redirect from  `/disability-evidence` to `/disability/how-to-file-claim/evidence-needed`, then they should be jumped to the section `What should the evidence show to support my disability claim`
    - @ncksllvn will need to create this redirect on the server-side, as well as the jump-to-section behavior.

**Comment by amycesal** [comment]
Just talked to @bethpotts .

I technically can make that update, but it would be better to track down the source file (the indesign or word doc where this came from) and make the change there. If anyone decides to update this form later, it will be good to have this change done in the source so it's preserved. 

However, if it takes too long to find the source, let me know, and I can make the change as a bandaid solution.

**Comment by ncksllvn** [comment]
Thanks @amycesal, that makes perfect sense. @bethpotts what do we need to make sure that happens? A follow-up ticket for making sure we get the updated PDF?

**Pull request merged**
