### PR TITLE
Va gov/content disability updates 526 mvp

### PR DESCRIPTION
**Pull request by ncksllvn**

### CODE REVIEW

**Comment by bethpotts** [comment]
@peggygannon It's not giving me a reviewer button to submit my approval, so I'm telling you this way: Approved!

**Comment by peggygannon** [comment]
@ncksllvn Hi, Nick this PR is ready for your review and if all looks good, please merge!

**Comment by peggygannon** [comment]
@bethpotts @ncksllvn Hi, I noticed this morning that my edits weren't in the /how-to-file-claim/ file, so I just fixed that file,  and re-commited them. 

This PR is ready for review, and then merge.

**Comment by peggygannon** [comment]
@ncksllvn @bethpotts Hi, there. I'm checking back on this PR and see when it will be merged into preview?

**Pull request merged**
