### PR TITLE
Va gov/content wip transition link

### PR DESCRIPTION
**Pull request by DanielleSoCompany**
Fixing this bug: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/14446

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @ncksllvn. I believe this is ready to merge. I did have to make one change to the left nav. I think I did it correctly, but haven't done that before so wanted to ask if you could review that specifically. Screenshots of those changes are below. Thank you!

image

image

**Comment by DanielleSoCompany** [comment]
@ncksllvn One more thing on this: We also need to update this link/label in the Mega Menu. See screenshot below. Is that something you can add to this PR, or would you like me to create a separate issue for it?

"Transitioning to Civilian Employment" changes to "VA Transition Assistance" and the link becomes: https://www.benefits.va.gov/tap/

image

**Comment by ncksllvn** [comment]
Hey @DanielleSoCompany! The update to the side nav looks good to me! 

Right now, the mega menu's configuration is in the `vets-website` repo still, so I had to open a PR over there to make that change - https://github.com/department-of-veterans-affairs/vets-website/pull/8916. Feel free to see the Heroku review instance there to confirm it looks okay!

**Comment by DanielleSoCompany** [comment]
Thank you @ncksllvn!!

**Pull request merged**
