### PR TITLE
Update breadcrumb to match the form title that's on the intro page

### PR DESCRIPTION
**Pull request by markgreenburg**
## Page to edit
url: `/disability-benefits/apply/form-526-all-claims/*`

## Origin of request (internal/stakeholder/user feedback):
Linked ticket

## Screehsot
screen shot 2019-01-29 at 2 06 43 pm

## Description of what's needed (edits/link changes/additions)
Updated the name of the form in the breadcrumb to match the form title we show people on the intro page.

### CODE REVIEW

**Comment by markgreenburg** [comment]
@peggygannon thanks - disability compensation is capitalized now.

**Comment by markgreenburg** [comment]
@peggygannon - please let me know if the new capitalization looks OK when you get a chance!

**Comment by markgreenburg** [comment]
Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16740

**Comment by peggygannon** [comment]
@markgreenburg Looks good. Thanks!

**Pull request merged**
