### PR TITLE
Add HCAv2 as a beta app

### PR DESCRIPTION
**Pull request by erikphansen**
~**DO NOT MERGE**~

~We plan to merge this first thing Monday morning so it goes out to prod with Monday's daily deployment.~

### To do:
- [x] Update copy when final copy is ready
- [x] Confirm we are ready to release this on prod

### CODE REVIEW

**Comment by erikphansen** [comment]
@ncksllvn Thanks! Yes, Danielle is going to provide the real copy for this page. And I've updated [my ticket for pushing the HCA changes](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/17721) to include steps to remove this beta app.

**Comment by erikphansen** [comment]
Here is a preview of the current WIP copy; we'll need real copy from @DanielleSoCompany

**Comment by Samara-Strauss** [comment]
@erikphansen put copy here https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18193

**Comment by erikphansen** [comment]
Just pushed up the changes. The page now looks like this (I will post another PR to update the button label from Title Case to Sentence case):

image

**Comment by erikphansen** [comment]
I just updated the PR, removing the landing page that would let users register for the HCAv2 beta since we are no longer releasing the feature as a beta app.

**Pull request merged**
