### PR TITLE
Tropical Storm Update for VA.gov Home page banner

### PR DESCRIPTION
**Pull request by Hampshire100**
## Page to edit
url:

### CODE REVIEW

**Comment by Hampshire100** [comment]
Sorry forgot to initially add Kelson Adams as a reviewer.

**Review by kelsonic — APPROVED** [review]

**Comment by kelsonic** [comment]
Thanks @Hampshire100, testing it locally now, will post a screenshot when I get it running before we merge 🙂

**Comment by kelsonic** [comment]
@Hampshire100 
image

Look ok?

**Comment by kelsonic** [comment]
Merging

**Pull request merged**
