### PR TITLE
Replace unique ul.vertical-list-group with ol.process.

### PR DESCRIPTION
**Pull request by kevwalsh**
## Page to edit
url: https://www.va.gov/disability/file-an-appeal/
After: https://vagov-content-pr-419.herokuapp.com/disability/file-an-appeal/

## Origin of request (internal/stakeholder/user feedback)
During anomaly discovery i found one use of   `<ul class="vertical-list-group more-bottom-cushion"> `where normally it would be an `<ol class="process">`

## Description of what's needed (edits/link changes/additions)
Change `<ul>` to `<ol>` and update `<li>` classes.

### CODE REVIEW

**Comment by kevwalsh** [comment]
@bethpotts here's a PR for converting a unique ul.vertical-list-group with ol.process.

**Comment by bethpotts** [comment]
@ncksllvn Can you look at the code changes to make sure all looks fine to you? I'm ready to merge this.

**Comment by bethpotts** [comment]
@ncksllvn Could you take a quick look at this one too? Also ready to merge this one now if all looks good to you.

**Comment by kevwalsh** [comment]
@bethpotts did you mean to leave your last comment on a different PR? it seems to repeat your earlier comment.

**Pull request merged**
