### PR TITLE
Content-wip-sign in style updates

### PR DESCRIPTION
**Pull request by bethpotts**
## Page to edit
url: https://www.va.gov/sign-in-faq/

## Origin of request (internal/stakeholder/user feedback)
style guide updates

## Description of what's needed (edits/link changes/additions)
sentence casing of H1 and subheads, service member, etc. (See style guide updates checklist)

### CODE REVIEW

**Comment by ncksllvn** [comment]
@bethpotts I had to resolve a bunch of conflicts here in commit 77e2cacdde749dfbb958b76addca0747ca558fc4. It was mostly just moving the periods outside of the link tags, but please double check me!

**Comment by ncksllvn** [comment]
To follow up on my prev comment, I'm pretty sure I resolved the conflicts wrong. It was very difficult to tell. Please take a look at https://github.com/department-of-veterans-affairs/vagov-content/commit/77e2cacdde749dfbb958b76addca0747ca558fc4 when you have time to evaluate the changes and correct the file if necessary.

**Comment by bethpotts** [comment]
@ncksllvn I can't tell where you resolved content conflicts. When I click on that link above, it's a huge list of changes. Did you only resolve periods, or could there be other content you think might have been changed in error? If it's just periods, we're good. I fixed some of those after your pass...

**Comment by ncksllvn** [comment]
Oof, sorry @bethpotts. Can you try this one? https://github.com/department-of-veterans-affairs/vagov-content/pull/387/commits/77e2cacdde749dfbb958b76addca0747ca558fc4

**Comment by bethpotts** [comment]
@ncksllvn Can you do a quick eyeball on this to make sure all looks good from your perspective?

**Pull request merged**
