### PR TITLE
Heading and title updates to Education, Pension, Life Insurance  and Records hubs

### PR DESCRIPTION
**Pull request by RLHecht**
## Page to edit
Pages in education, pension, life insurance, and records hubs

## Description of what's needed (edits/link changes/additions)

Adding heading tag and sentence casing it to each page in education, pension, life insurance and records hubs and title capping all titles on these pages. 

Working in this branch: content-wip-heading-title-updates

### CODE REVIEW

**Comment by peggygannon** [comment]
@Karak888 I worry about merging in this PR, as it also contains updates for Life Insurance and Pension (which have already been migrated). I'm not sure how to handle, as I don't want to overwrite any of the migration work on Pension and Life Insurance.

**Comment by Karak888** [comment]
@ncksllvn resident expert of all things, can you help Peggy with this please?

**Comment by ncksllvn** [comment]
@Karak888 @peggygannon If a page has already been migrated into the CMS but we're interested in apply the changes in a pull request to that page, then sadly we'll have to manually recreate the changes in the CMS. Once a page is in the CMS, vagov-content changes won't affect it and the vagov-content page itself is stale. The CMS team defined content freezes specifically to avoid this.

Are we interested in the changes here? Or just worried about merging a pull request that changes a page already in the CMS?

**Comment by peggygannon** [comment]
thanks, @ncksllvn I think we should close this PR, as it's very confusing to have different hubs covered in this PR. Three of these hubs have already been migrated to Drupal (Pension, Life Insurance, and Records). 

EDU is the only one that is left and that content freeze is 8/1. As such, i think we'll have to recreate the EDU changes in drupal, as it's too confusing to have different hubs in one PR. 

cc @Karak888

**Comment by peggygannon** [comment]
@Karak888 I'm closing this out, as it contains work for 4 hubs, three of which have already been migrated to drupal. 

Any changes to EDU will have to be replicated in drupal.

**Pull request closed without merging**
